/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmployeeTrackRouteImport } from './routes/employee.track'
import { Route as EmployeeSubmitRouteImport } from './routes/employee.submit'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeeMyRouteImport } from './routes/employee.my'
import { Route as EmployeeLoginRouteImport } from './routes/employee.login'
import { Route as AdminWorkflowRouteImport } from './routes/admin.workflow'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuggestionsRouteImport } from './routes/admin.suggestions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminPlantsRouteImport } from './routes/admin.plants'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMastersRouteImport } from './routes/admin.masters'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDatabaseRouteImport } from './routes/admin.database'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminSuggestionsIndexRouteImport } from './routes/admin.suggestions.index'
import { Route as AdminSuggestionsIdRouteImport } from './routes/admin.suggestions.$id'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeTrackRoute = EmployeeTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSubmitRoute = EmployeeSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeMyRoute = EmployeeMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLoginRoute = EmployeeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminWorkflowRoute = AdminWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuggestionsRoute = AdminSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlantsRoute = AdminPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMastersRoute = AdminMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabaseRoute = AdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuggestionsIndexRoute = AdminSuggestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSuggestionsRoute,
} as any)
const AdminSuggestionsIdRoute = AdminSuggestionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSuggestionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plants': typeof AdminPlantsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggestions': typeof AdminSuggestionsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/employee/my': typeof EmployeeMyRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/submit': typeof EmployeeSubmitRoute
  '/employee/track': typeof EmployeeTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/suggestions/$id': typeof AdminSuggestionsIdRoute
  '/admin/suggestions/': typeof AdminSuggestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plants': typeof AdminPlantsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/employee/my': typeof EmployeeMyRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/submit': typeof EmployeeSubmitRoute
  '/employee/track': typeof EmployeeTrackRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/admin/suggestions/$id': typeof AdminSuggestionsIdRoute
  '/admin/suggestions': typeof AdminSuggestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plants': typeof AdminPlantsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggestions': typeof AdminSuggestionsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/employee/my': typeof EmployeeMyRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/submit': typeof EmployeeSubmitRoute
  '/employee/track': typeof EmployeeTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/suggestions/$id': typeof AdminSuggestionsIdRoute
  '/admin/suggestions/': typeof AdminSuggestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/employee'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/database'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/locations'
    | '/admin/masters'
    | '/admin/notifications'
    | '/admin/plants'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/suggestions'
    | '/admin/users'
    | '/admin/workflow'
    | '/employee/login'
    | '/employee/my'
    | '/employee/notifications'
    | '/employee/profile'
    | '/employee/submit'
    | '/employee/track'
    | '/admin/'
    | '/employee/'
    | '/admin/suggestions/$id'
    | '/admin/suggestions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/database'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/locations'
    | '/admin/masters'
    | '/admin/notifications'
    | '/admin/plants'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/workflow'
    | '/employee/login'
    | '/employee/my'
    | '/employee/notifications'
    | '/employee/profile'
    | '/employee/submit'
    | '/employee/track'
    | '/admin'
    | '/employee'
    | '/admin/suggestions/$id'
    | '/admin/suggestions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/employee'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/database'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/locations'
    | '/admin/masters'
    | '/admin/notifications'
    | '/admin/plants'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/suggestions'
    | '/admin/users'
    | '/admin/workflow'
    | '/employee/login'
    | '/employee/my'
    | '/employee/notifications'
    | '/employee/profile'
    | '/employee/submit'
    | '/employee/track'
    | '/admin/'
    | '/employee/'
    | '/admin/suggestions/$id'
    | '/admin/suggestions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/track': {
      id: '/employee/track'
      path: '/track'
      fullPath: '/employee/track'
      preLoaderRoute: typeof EmployeeTrackRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/submit': {
      id: '/employee/submit'
      path: '/submit'
      fullPath: '/employee/submit'
      preLoaderRoute: typeof EmployeeSubmitRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/my': {
      id: '/employee/my'
      path: '/my'
      fullPath: '/employee/my'
      preLoaderRoute: typeof EmployeeMyRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/login': {
      id: '/employee/login'
      path: '/login'
      fullPath: '/employee/login'
      preLoaderRoute: typeof EmployeeLoginRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/workflow': {
      id: '/admin/workflow'
      path: '/workflow'
      fullPath: '/admin/workflow'
      preLoaderRoute: typeof AdminWorkflowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suggestions': {
      id: '/admin/suggestions'
      path: '/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AdminSuggestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plants': {
      id: '/admin/plants'
      path: '/plants'
      fullPath: '/admin/plants'
      preLoaderRoute: typeof AdminPlantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/masters': {
      id: '/admin/masters'
      path: '/masters'
      fullPath: '/admin/masters'
      preLoaderRoute: typeof AdminMastersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/database': {
      id: '/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminDatabaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suggestions/': {
      id: '/admin/suggestions/'
      path: '/'
      fullPath: '/admin/suggestions/'
      preLoaderRoute: typeof AdminSuggestionsIndexRouteImport
      parentRoute: typeof AdminSuggestionsRoute
    }
    '/admin/suggestions/$id': {
      id: '/admin/suggestions/$id'
      path: '/$id'
      fullPath: '/admin/suggestions/$id'
      preLoaderRoute: typeof AdminSuggestionsIdRouteImport
      parentRoute: typeof AdminSuggestionsRoute
    }
  }
}

interface AdminSuggestionsRouteChildren {
  AdminSuggestionsIdRoute: typeof AdminSuggestionsIdRoute
  AdminSuggestionsIndexRoute: typeof AdminSuggestionsIndexRoute
}

const AdminSuggestionsRouteChildren: AdminSuggestionsRouteChildren = {
  AdminSuggestionsIdRoute: AdminSuggestionsIdRoute,
  AdminSuggestionsIndexRoute: AdminSuggestionsIndexRoute,
}

const AdminSuggestionsRouteWithChildren =
  AdminSuggestionsRoute._addFileChildren(AdminSuggestionsRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDatabaseRoute: typeof AdminDatabaseRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMastersRoute: typeof AdminMastersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlantsRoute: typeof AdminPlantsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuggestionsRoute: typeof AdminSuggestionsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowRoute: typeof AdminWorkflowRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDatabaseRoute: AdminDatabaseRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMastersRoute: AdminMastersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlantsRoute: AdminPlantsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuggestionsRoute: AdminSuggestionsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowRoute: AdminWorkflowRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeRouteChildren {
  EmployeeLoginRoute: typeof EmployeeLoginRoute
  EmployeeMyRoute: typeof EmployeeMyRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeSubmitRoute: typeof EmployeeSubmitRoute
  EmployeeTrackRoute: typeof EmployeeTrackRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeLoginRoute: EmployeeLoginRoute,
  EmployeeMyRoute: EmployeeMyRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeSubmitRoute: EmployeeSubmitRoute,
  EmployeeTrackRoute: EmployeeTrackRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
